import type { Metadata } from 'next';
import { Inter, Modern_Antiqua, Noto_Serif } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'], variable: '--font-inter' });

const noto_serif = Noto_Serif({
  subsets: ['latin'],
  variable: '--font-noto_serif',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${noto_serif.variable}`}>
        {children}
      </body>
    </html>
  );
}
